spring.application.name=gateway
server.port=8080
# expõe todos os endpoints do actuator
management.endpoints.web.exposure.include=*
# management.endpoints.web.exposure.include=health,metrics,prometheus

# habilita o prometheus
management.prometheus.metrics.export.enabled=true

# definição de rotas
spring.cloud.gateway.routes[0].id=user-service
spring.cloud.gateway.routes[0].uri=lb://USER-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/user/**

spring.cloud.gateway.routes[1].id=chat-service
spring.cloud.gateway.routes[1].uri=lb://USER-SERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/chat/**