spring:
  application:
    name: gateway
  # definição de rotas
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user/**

        - id: chat-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/chat/**

server:
  port: 8080
# expõe todos os endpoints do actuator
management:
  endpoints:
    web:
      exposure:
        # include: "*"
        include: health,metrics,prometheus
  # habilita o prometheus
  prometheus:
    metrics:
      export:
        enabled: true
