server.port=8090

spring.application.name=ai-service

## open ai
# spring.ai.openai.api-key=${OPEN_AI_KEY}
# spring.ai.openai.model=gpt-3.5-turbo

## gemini
spring.ai.model.chat=google-genai
spring.ai.google.genai.api-key=${GEMINI_API_KEY}
spring.ai.google.genai.chat.options.model=gemini-2.5-flash

# ollama
spring.ai.ollama.base-url=http://localhost:11434

# rag
spring.ai.ollama.embedding.options.model=nomic-embed-text

# config do eureka
eureka.instance.prefer-ip-address=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# expõe todos os endpoints do actuator
management.endpoints.web.exposure.include=*
# management.endpoints.web.exposure.include=health,metrics,prometheus

# habilita o prometheus
management.prometheus.metrics.export.enabled=true

# tentativa de usar gemini para embedding
# spring.ai.model.embedding.text=google-genai
# spring.ai.google.genai.embedding.text.options.model=text-embedding-004
# spring.ai.google.genai.project-id=0579743248
# spring.ai.google.genai.project-id=teste
# debug=true