spring.application.name=user-service
server.port=8081

# expõe todos os endpoints do actuator
management.endpoints.web.exposure.include=*
# management.endpoints.web.exposure.include=health,metrics,prometheus

# habilita o prometheus
management.prometheus.metrics.export.enabled=true

# config do eureka
eureka.instance.prefer-ip-address=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka