spring.application.name=eureka-server
server.port=8761
# garante que o eureka não tente registrar ele mesmo
eureka.client.register-with-eureka=false
# garante que o eureka não tente baixar o catagolo de outro eureka
eureka.client.fetch-registry=false

# para desabilitar logs
# logging.level.com.netflix.eureka=OFF
# logging.level.com.netflix.discovery=OFF

# expõe todos os endpoints do actuator
management.endpoints.web.exposure.include=*
# management.endpoints.web.exposure.include=health,metrics,prometheus

# habilita o prometheus
management.prometheus.metrics.export.enabled=true